import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
export default function Dictionary(props) {
  const [settingshow, setsettingshow] = useState(props.setting)
  useEffect(() => {
    let bodyElement = document.getElementsByTagName('body')[0];
    bodyElement.className = "Dashbord";
  })
  return (
    <>
     

      <div className="mainbox">


      <Link className="navbar-brand" to="/"> <img src="./images/back-btn.png" class="extbtn mart20p" alt="..." height="30px" width="30px"></img></Link>

        <div className='dict'>
          
        <div class="col-lg-12">
					
                    <h1 class="privacy-policy">User terms &amp; conditions</h1>
                    <div class="about-bot">
                       <p>Effective Date: July 1 2021</p>
                       <p>PLEASE READ THESE TERMS &amp; CONDITIONS (“TERMS”) BEFORE USING THE SERVICES. THEY ARE THE RULES AND REQUIREMENTS THAT APPLY TO THE SERVICES. DO NOT PURCHASE A SUBSCRIPTION, REGISTER FOR AN ACCOUNT, OR USE THE SERVICES IF YOU ARE NOT IN AGREEMENT WITH THESE TERMS.</p>
                       <h2 class="terms-marg">CONTROLLER IDENTIFICATION</h2>
                       <p>We inform you that the provided data, will be processed by The Never Ending Game Ltd. with registered office 31 Stanhope Drive, Horsforth, Leeds LS18 4ES (hereinafter as the “Controller”) with the following purposes: You can contact the Controller through the following URL: <a href="https://ne-games.com" target="_blank">ne-games.com</a>.</p>
                       <p>Welcome to The Never Ending Game, which is owned and operated by The Never Ending Game Ltd. (“Company,” “we,” “us” or “our”). By purchasing a subscription to, registering anaccount for, or using www.theneverendingwordgame.com, including all of the services provided therein, including any specific functionalities of our products and/or services and any other websites and applications that link to these Terms (collectively, the “Services”), you acknowledge that you have read and understood these Terms, and agree to be bound by them. Both these Terms and separate terms of service or sale documents may apply to your use of the Services or to a sweepstakes, service or product offered via the Services (“Additional Terms”). To the extent there is a conflict between these Terms and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly state otherwise. In these Terms, “you” refers to Adult Users of the Services and purchasers of accounts. An “Adult” is a person of legal age who can enter into a contract; by or using the Services, you represent and warrant that you are an Adult, and that you will be responsible for ensuring that any child or student authorized by you to use and access the Services does so in accordance with these Terms.</p>
                       <p>These terms are intended for parents, guardians or anyone in legal charge of and supervision of children and users of the services.</p>
                       <p>Company collection, use and disclosure, if any, of information collected from you or a child authorized by you is detailed in the (<a href="https://ne-games.com/privacy_policy" target="_blank">Privacy Policy</a>), which is incorporated by reference and made a part of these Terms.</p>
                       <h2 class="terms-marg">Summary of Key Points</h2>
                       <p>You should read all of these Terms and also our Privacy Policy (the terms of which are incorporated into these Terms), but here are some key points:</p>
                       <ul className='list-privacy'>
                          <li>By purchasing a subscription to, registering an account for, or using the Services, including any specific functionalities of our products and/or services, you accept these Terms.</li>
                          <li>We currently offer our Services for:</li>
                          <li>Families – through Family User Accounts; and</li>
                          <li>Schools – through School Generated Accounts;</li>
                          <li>By activating an Account, you agree that we may renew your subscription automatically for the same subscription term on the day after your previous subscription ends, and you authorize us to charge you for the subscription term, unless you cancel your Account prior to its renewal date through the procedures described in the “Subscription Cancellation” section 2.C.iii.</li>
                          <li>YOU AGREE TO ARBITRATE DISPUTES RATHER THAN GOING TO COURT.</li>
                          <li>Your use of the Services is AS IS, without warranty and will result in no liability to us.</li>
                       </ul>
                       <h2 class="terms-marg">Table of Contents</h2>
                       <ol class="terms-ol list-privacy">
                          <li><a href="https://lingokids.com/terms-of-service#1.%20Description%20of%20Services." target="_blank">Description of Services.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#2.%20Accounts,%20Passwords,%20and%20Payments." target="_blank">Accounts, Passwords, and Payments.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#3.%20Services%20Ownership%20and%20License." target="_blank">Services Ownership and License.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#4.%20Content%20You%20Submit." target="_blank">Content You Submit.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#5.%20Services%20and%20Content%20Use%20Restrictions." target="_blank">Services and Content Use Restrictions.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#6.%20Linking%20to%20and%20from%20Our%20Services." target="_blank">Linking to and from Our Services.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#7.%20Governing%20Law/Jurisdiction." target="_blank">Governing Law/Jurisdiction.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#8.%20Disclaimer%20of%20Representations%20and%20Warranties." target="_blank">Disclaimer of Representations and Warranties.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#9.%20Limitations%20of%20Liability." target="_blank">Limitations of Liability.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#10.%20Indemnity." target="_blank">Indemnity.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#11.%20Infringement%20Policy%20and%20Reporting%20Procedure." target="_blank">Infringement Policy and Reporting Procedure.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#12.%20Wireless%20Features." target="_blank">Wireless Features.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#13.%20Submission%20of%20Feedback." target="_blank">Submission of Feedback.</a></li>
                          <li><a href="https://lingokids.com/terms-of-service#14.%20General%20Provisions." target="_blank">General Provisions.</a></li>
                       </ol>
                       <h2 class="terms-marg">1. Description of Services</h2>
                       <p>As part of the Services, we provide a platform via our website <a href="https://ne-games.com" target="_blank">ne-games.com</a> and various related games, applications, features, content.</p>
                       <p>Users of the Services (“Users”) include “Child Users” or ”pupils” or “Students”, “Adult Users” (including parents and guardians or anyone in legal charge of and supervision of Child Users, teachers and school administrators).</p>
                       <h2 class="terms-marg">2. Accounts, Passwords, and Payments</h2>
                       <p>A. Account Types. We currently offer the following types of accounts through the Services: Individual “over 18” accounts, Family Accounts and Teacher Accounts (collectively,“ Accounts”).</p>
                       <p>(i) Individual “over 182 accounts Accounts. A single account for a person aged over 18 and legally allowed to own a credit card in their own name.</p>
                       <p>(ii) Family Accounts. A Family Account can have a maximum of five users, including an Adult User and up to four Child Users that Adult Users add to the Family Account.</p>
                       <p>(iii) School Accounts. School Accounts may only be registered by an Adult currently employed (on the teaching or administration staff of a school, school district, licensed childcare facility, or other licensed educational institution or program (“Educational Institution”). The registering person’s employment status must be independently verifiable, and must only use or facilitate the use of the School Account for pupils/students at the Educational Institution for which that registering person has authorisation. By registering for a School Account, you represent and warrant that (a) you have permission from your School / Educational Institution to enter into these Terms on its behalf, and to use the Services as part of learning activities, and (b) your use of the Services and provision of student data through the Services is compliant with any obligations you and your Educational Institution have under applicable laws, including without limitation the Family Educational Rights and Privacy Act. If at any point in time you no longer are employed at, or have permission to use the Services from, your School / Educational Institution, you agree that you will notify Company immediately. School Accounts accounts and associated packages are offered in the sole discretion of Company and we reserve the right to decline to issue, cancel, or change the terms and / or conditions of any or all School Accounts at any time for any reason, except with respect to the collection, use, and
                          disclosure of Child User information,
                          which we will treat in accordance with our Privacy Policy.
                       </p>
                       <p>B. Passwords and Account Access. Every Account has one designated Adult User (the registering person) who must be at least 18 years of age. You are responsible for maintaining the confidentiality of your password and Account information. You agree (a) that you will provide complete accurate registration information about yourself (agreed between us) and any individual you authorise to access your Account (also agreed between us) and keep your Account information up - to - date, (b) that you are solely responsible for all activities that occur under your Account, (c) to notify us immediately of any unauthorised Account use, (d) that we are in no way responsible for any loss that you may incur as a result of any unauthorised use of your Account and password, and (e) that you will not sell, transfer, or assign your Account or any Account rights. If we learn that an ineligible user has created an Account, we may seek confirmation of the user’s status or deactivate the Account.</p>
                       <p>C. Account Fees. For certain types of Accounts, we may charge a fee, such as an Account fee or subscription fee. For existing subscribers, we may change your fee at any time at our sole discretion at the end of your subscription period. All fees are payable in accordance with payment terms in effect at the time the fee or the charge becomes payable. We may offer promotional trial subscriptions to access the Services for free or at special discounted prices. If you sign up for a trial subscription, your rights to use the Services are limited by the terms of such trial and will terminate or renew according to the terms of your trial arrangement and / or any applicable Additional Terms. Please note that we do not provide price protection or refunds for existing subscribers in the event of a price drop or promotional offering for new subscribers.</p>
                       <p>(i) Authorization to Charge for Services. You must either use a credit card, debit card or other payment mechanism accepted by us (e.g., Google Play Store, Apple’s iTunes App Store) (“Pay Mechanism”) to activate and maintain a paid Account. You authorize us to charge you through the Pay Mechanism that you use when registering for an Account. You will also be responsible for charges for any products or services that you order that are offered for sale through the Services including any specific functionalities of our products and/or services, such as “hints”. If we do not receive payment from the Pay Mechanism you use, you agree to pay all amounts due hereunder upon our demand and will be solely responsible for any dispute with your payment provider. Should the Pay Mechanism provided initially be declined for insufficient funds or any other reason, we reserve the right to attempt to recharge the Pay Mechanism in full or in lesser instalments of the initially incurred charge. You will not be charged more than the amount for which you purchased your Account subscription. You will be solely responsible for all overdraft fees and/or penalties that may be assessed by your payment provider. We use a third - party service provider to process payments on our behalf. You acknowledge and agree that in the event the third - party payment processor experiences a data breach that affects your information through no fault of Company, Company will in no way be responsible or liable to you for any such breach.</p>
                       <p>(ii) Subscription Renewal. By activating an Account, you agree that we may renew your subscription automatically for the same subscription term on the day after your previous subscription ends, and you authorize us to charge you for the subscription term, unless you cancel your Account prior to its renewal date through the procedures described in the “Subscription Cancellation” section below. We will charge your credit card (or the other method of payment initially used by you) each year, month, or other applicable period (depending on the term that you selected) for the then - current applicable price.</p>
                       <p>(iii) Subscription Cancellation. Unless you purchased your subscription through Apple’s iTunes App Store, to cancel your subscription and avoid future billing, you may cancel your Account prior to its renewal date through the Manage My Subscription area in the Schools / Family Section of the App or by contacting our Customer Support team. If you do so, please know that we endeavour to have customer requests handled within 24 hours; however, we cannot guarantee that your cancellation will be registered within that time period. We will honour all cancellations received before the renewal date, outside of iTunes App Store subscriptions. If you downloaded our app through Apple’s iTunes App Store, you must follow the cancellation instructions pro vided in the iTunes App Store. For all Accounts, you will continue to have access to your Account for the period of time that has already been prepaid. If you activated a paid Account at a discounted or promotional rate, chose to pay in instalments, and then cancelled that Account prior to all of the instalments having been paid, the period of time after the cancellation that your Account will continue to be accessible will be calculated based on the non - promotional / non - discounted rate in effect at the time of cancellation. After you cancel your Account, we will not charge you any subscription fees after the expiration of your then - current subscription. Please note we do not provide full or partial refunds for prepaid sums. In any event, you will be able to continue to use the Services throughout the remainder of the subscription period for which you have already paid.</p>
                       <p>(iv) Refunds. If you sign up for a trial subscription through a Pay Mechanism that is NOT through Apple’s iTunes App Store, you are entitled to a refund for any fees paid for your Account within 7 days of the payment date. After the 7th day, you are not entitled to any refund. If your Account includes any additional add on services, you are not entitled to any refund.</p>
                       <h2 class="terms-marg">3. Services Ownership and License</h2>
                       <p>A. Ownership. As between us and you, the Services, including any specific functionalities of our products and/or Services (including past, present and future versions) are owned and controlled by us and their Content is protected by copyright, trademark, trade dress, patent, and other intellectual property rights and laws to the fullest extent possible. “Content” means all text, graphics, user interfaces, visual interfaces, photographs, logos, sounds, music, artwork, and computer code displayed on or available through the Services and the design, structure, selection, coordination, expression, and arrangement of such materials including, trademarks, logos, trade names, service marks, and trade identities of various parties, including ours (collectively, “Trademarks”); and (iii) other forms of intellectual property.</p>
                       <p>B. Limited License. Subject to your strict compliance with these Terms and your payment of any applicable subscription fees, we grant you a limited, non - exclusive, revocable, non - assignable and non - transferable license (“License”) to access, display, view, use, the Content on a personal computer, mobile phone or other wireless device, or other Internet - enabled device (each, an “Internet Device”) for your personal, non - commercial use only (e.g., teachers may use Content from the Services, including any specific functionalities of our products and/or services, for educating their students and other users’ use is limited to personal use). The License does not give you any ownership of, or any other intellectual property interest in, any Content or the Services including any specific functionalities of our products and/or services, and you cannot otherwise use the Content or the Services without our express prior written permission. All rights not expressly granted to you are reserved by us and/or our licensors and other third parties. Except as expressly provided in these Terms or with Company’s express prior written consent, no part of the Services and no Content may be used, copied, reproduc ed, distributed, uploaded, posted, publicly displayed, translated, transmitted, broadcasted, sold, licensed or otherwise exploited for any purpose whatsoever. Any unauthorized use of any Content or the Services for any purpose is prohibited.</p>
                       <h2 class="terms-marg">4. Services and Content Use Restrictions</h2>
                       <p>You agree that you will not: (i) engage in any activities that (a) attempt to or do harm to us, the Services, including any specific functionalities of our products and/or services, or any others; (b) are unlawful, false, in accurate, misleading, offensive, obscene, lewd, violent, harassing, threatening, abusive, tortious, defamatory, invasive of another’s privacy, or are otherwise objectionable to us, in our sole discretion; or (c) violate any right of any third party; (ii) You and Students / pupils shall not disparage Company’s performance, or distribute any false or misleading statement or otherwise take any action which could reasonably be expected to adversely affect the personal or professional reputation of Company or Company’s employees. (iii) reverse engineer, disassemble, or modify any source or object code or any software or other products, services, or processes accessible through the Services, including any specific functionalities of our products and/or services, install any software, file, or code on the Services that is not authorized by Company, or attempt to do so; (iv) engage in any activity that interferes with a user’s access to the Services or the proper operation of the Services; (v) access or collect information from the Services using automated means (such as through scripts, robots scrapers, or spiders); (vi) use any meta tags or other “hidden text” utilizing any of our Trademarks; (vii) interfere with or circumvent any security feature of the Services or any feature that restricts or enforces limitations on the use of or access to the Services, any specific functionalities of our products and/or services, or its Content; (viii) use the Services for commercial or political purposes; (ix) disclose, harvest, or otherwise collect information, including email addresses, or other private information about any third party without that party’s express consent; or (x) otherwise violate these Terms, or any Additional Terms, or solicit, encourage, or facilitate anyone else to do so.</p>
                       <h2 class="terms-marg">5. Linking to and from Our Services</h2>
                       <p>A. Linking to or Framing Our Services. When linking to our Services, you must adhere to the following requirements: (i) the link to the Services must not damage, disparage, present false information abo ut or tarnish the goodwill associated with any of our Trademarks, products, services and/or intellectual property; (ii) the link to the Services must not create the false appearance that your websites and/or organization is sponsored by, endorsed by, affiliated with, or associated with us; (iii) no one may “frame” the Services or create a browser environment around any of the Content and (iv) you may not link to the Services from a website that is unlawful, abusive, indecent, or obscene; that promotes violence or illegal acts; that contains expressions of racism; that is libelous, defamatory, scandalous, or inflammatory; or that we otherwise deem inappropriate in our sole discretion. We reserve the right to prohibit linking to the Services for any reason, in our sole and absolute discretion, even if the linking complies with the requirements described above.</p>
                       <p>B. Links to Other Services and Third Parties. Child / student Users are blocked from accessing internal links to in - house purchases and external links, including those corresponding to any pop- up ads or other advertisements directed at children or unless a School / Educational Establishment Registrar or Adult User gives permission to said access. Any interactions, transactions, and other dealings that you have with any third parties found on or through the Services (including those that are linked to from the Services) are solely between you and the third party (including issues related to payments, delivery of goods and warranties), and we disclaim all liability in connection therewith.</p>
                       <h2 class="terms-marg">6. Governing Law / Jurisdiction</h2>
                       <p>A. Governing Law/Jurisdiction. THESE TERMS, AND ANY ADDITIONAL TERMS, WILL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE UNITED KINGDOM, WITHOUT REGARD TO ITS CONFLICTS OF LAWS PRINCIPLES.</p>
                       <p>B. Arbitration and Dispute Resolution. If any controversy, allegation, or claim arises out of or relates to the Services or these Terms (collectively, “Dispute”), you and we agree to the following resolution process with respect to the Dispute. To most efficiently resolve any Dispute, you and we agree to first discuss the Dispute informally for at least thirty (30) days. To do so, the party who wants to raise the Dispute must first send to the other party a notice that must include (1) a description of the Dispute and (2) a proposed resolution (together, the “Dispute Notice”). If you want to raise a Dispute, you must send your Dispute Notice by certified mail to us at: 31 Stanhope Drive, Horforth, Leeds LS18 4ES. If we would like to subsequently discuss your Dispute Notice with you, we will contact you by using contact information included with your Dispute Notice. If we want to raise a Dispute, we will send our Dispute Notice to you at the email address we have on file for you. If we do not have avalid email address on file for you, we will send our Dispute Notice to you through certified mail.</p>
                       <p>If you and Company do not reach an agreed - upon resolution within 30 days of receipt of the Dispute Notice, you and Company agree that the Dispute will be resolved solely by binding arbitration in accordance with the British Civil Court System – for details go to <a href="https://www.gov.uk/make-court-claim-for-money" target="_blank">:https://www.gov.uk/make-court-claim-for-money</a></p>
                       <p>C. Injunctive Relief. The foregoing provisions of this Section 6 will not apply to any legal action taken by either party to seek an injunction or other equitable relief in conjunction with any intellectual property claim or claim related to unauthorized access to data through the Services (including, but not limited to, claims related to patent, copyright, trademark, and trade secrets, and claims relating to the access or retrieval of data through the Services, including through any specific functionalities of our products and/or services, using an automated process such as scraping).</p>
                       <p>D. Timing of Claim. To help resolve any issues between you and us promptly and directly, you and Company agree that any Dispute Notice must be sent, or that any small claims or injunctive relief complaint permitted under this Section 6 must be filed, within one year after the events giving rise to the Dispute arise; otherwise, the Dispute is waived.</p>
                       <p>E. No Class Actions. You and Company agree that any Disputes will be arbitrated only on an individual basis and will not be consolidated with any other arbitrations or other proceedings that involve any claim or controversy of any other party.</p>
                       <h2 class="terms-marg">8. Disclaimer of Representations and Warranties</h2>
                       <p>YOUR ACCESS TO AND USE OF THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES ARE PROVIDED ON AN “AS IS,” “AS AVAILABLE,” AND “WITH ALL FAULTS” BASIS. Therefore, to the fullest extent permissible by law, we and our parent, and each of their respective employees, officers, directors, members, managers, shareholders, agents, vendors, licensors, licensees, contractors, customers, successors, and assigns (collectively, “Company Parties”), hereby disclaim and make no representations, warranties, endorsements, or promises, express or implied, as to:</p>
                       <p>The Services (including the Content and the User - Generated Content); The functions, features, including any specific functionalities of our products and/or services, or any other elements on, or made accessible through, the Services; Any products, services, or instructions offered or referenced at or linked through the Services; Whether the Services (and their Content), or the servers that make the Services available, are free from any harmful components (including viruses, Trojan horses, and other technologies that could adversely impact your Internet Device); The specific availability of the Services, and whether any defects in the Services will be repaired, or will be repaired in a particular time frame; and Whether your use of the Services is lawful in any particular jurisdiction.</p>
                       <p>EXCEPTING ONLY AS MAY BE SPECIFICALLY SET FORTH IN ANY ADDITIONAL TERMS, THE COMPANY PARTIES HEREBY FURTHER DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON - INFRINGEMENT OR MISAPPROPRIATION OF INTELLECTUAL PROPERTY RIGHTS OF THIRD PARTIES, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION, AND FREEDOM FROM ERRORS, COMPUTER VIRUSES OR OTHER HARMFUL ELEMENTS.</p>
                       <p>Some jurisdictions limit or do not allow the disclaimer of implied or other warranties, so the above disclaimers may not apply to the extent that such jurisdictions’ laws are applicable.</p>
                       <h2 class="terms-marg">9. Limitations of Liability</h2>
                       <p>UNDER NO CIRCUMSTANCES WILL ANY COMPANY PARTIES BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGES OF ANY KIND, including personal injury or death or for any direct, indirect, economic, exemplary, special, punitive, incidental, or consequential losses or damages that are directly or indirectly related to:</p>
                       <p>The Services (including the Content and the User - Generated Content and any specific functionalities of our products and/or services); Your use of or inability to use the Services, or the performance of the Services; The failure of a child user to learn or otherwise benefit educationally from their use of the Services; Any action taken in connection with an investigation by Company Parties or law enforcement authorities regarding your access to or use of the Services, including any specific functionalities of our products and/or services; Any action taken in connection with copyright or other intellectual property owners or other rights owners; Any errors or omissions in the Services’ technical operation; or Any damage to any user’s computer, hardware, software, modem, or other equipment or technology, including damage from any security breach or from any virus, bugs, tampering, fraud, error, omission, interruption, defect, delay in operation or transmission, computer line, or network failure or any other technical or other malfunction, including losses or damages in the form of lost profits, loss of goodwill, loss of data, work stoppage, inaccuracy of results, or equipment failure or malfunction.</p>
                       <p>The foregoing limitations of liability will apply even if any of the events or circumstances were foreseeable and even if Company Parties were advised of or should have known of the possibility of such losses or damages, regardless of whether you bring an action of contract, negligence, strict liability, or tort (including whether caused, in whole or in part, by negligence, force majeure, telecommunications failure, or destruction of the Services).</p>
                       <p>Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages of the sort that are described above, so the above limitation or exclusion may not apply to you.</p>
                       <p>EXCEPT AS MAY BE PROVIDED IN ANY ADDITIONAL TERMS, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL COMPANY PARTIES’ TOTAL LIABILITY TO YOU IN CONNECTION WITH YOUR ACCESS TO AND USE OF THE SERVICES AND YOUR RIGHTS UNDER THESE TERMS EXCEED THE AMOUNT PAID BY YOU TO US DURING THE PREVIOUS TWELVE MONTHS FOR ALL POSSIBLE DAMAGES, LOSSES, AND CAUSES OF ACTION.</p>
                       <h2 class="terms-marg">10. Indemnity</h2>
                       <p>To the maximum extent allowed by law, you agree to indemnify, defend and hold harmless the Company Parties from and against all losses, expenses, damages and costs, including reasonable attorneys’ fees, resulting from: (a) your breach or alleged breach of these Terms; (b) your use of the Services or activities in connection with the Services, including any specific functionalities of our products and/or services; (c) your User - Generated Content; (d) your violation of any law, rule or regulation; or (e) your violation of any third party rights. The Company Parties reserve the right to assume, at their sole expense, the exclusive defence and control of any matter subject to indemnification by you, in which event you will fully cooperate with the Company Parties in asserting any available defences. You will not, in any event, settle any claim without our prior written consent. If any child you authorise to use or access the Services disaffirms any or all of these Terms, you agree to defend, indemnify and hold us harmless for any damages we suffer by the child’s disaffirmance.</p>
                       <h2 class="terms-marg">11. Infringement Policy and Reporting Procedure</h2>
                       <p>In accordance with the Digital Millennium Copyright Act of 1998 (the “DMCA”), our designated agent to receive notices of copyright infringement is Graham Jaggers, who may be reached via <b>info@ne-games.com</b>, or by postal mail to 31 Stanhope Drive, Horsforth, Leeds LS18 4ES. If you believe that your material has been posted on, or distributed via, the Services in a way that constitutes copyright infringement, please provide the following information as required by the DMCA: (i) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed (the “complaining party”); (ii) identification of the copyright work(s) claimed to have been infringed; (iii) identification of the material that is claimed to be infringing or to be the subject of infringing activity and information reasonably sufficient to permit us to locate the material; (iv) information reasonably sufficient to permit us to contact the complaining party; (v) a statement that the complaining party (name, address, telephone number, and email address) has a good - faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (vi) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. The DMCA provides that a person who knowingly materially misrepresents that material or an activity is infringing may be subject to liability. We may send the information in the notice from the complaining party to the person who provided the allegedly infringing material.</p>
                       <h2 class="terms-marg">12. Wireless Features</h2>
                       <p>A. Wireless Features. Your carrier may charge standard messaging, data, and other fees, which may appear on your wireless bill or be deducted from your prepaid balance. Your carrier may prohibit or restrict certain Wireless Features, and certain Wireless Features may be incompatible with your carrier or wireless Internet Device. You agree that as to the Wireless Features for which you are registered, we may send communications to your wireless Internet Device regarding us or other parties. If you have registered via the Services for Wireless Features, then you agree to notify us of any changes to your wireless number (including phone number) and update your Account to reflect the changes.</p>
                       <h2 class="terms-marg">13. Submission of Feedback</h2>
                       <p>Under certain circumstances, we might ask Adult Users for feedback or ideas as to their experiences with our Services including with specific functionalities of our products. If you choose to provide us with feedback, you acknowledge and agree (i) that you have no expectation of review, compensation, or consideration of any type for any such feedback or ideas, and (ii) we will be free to use and exploit such feedback or ideas in our discretion and without compensation or obligation to you.</p>
                       <h2 class="terms-marg">14. General Provisions</h2>
                       <p>A. Termination and Suspension. We reserve the right to discontinue the Services or suspend or terminate your access to it, including any Accounts or User - Generated Content submitted by you, at any time, without notice, for any reason and without any obligation to you or any third party. If any information that you provide, or if we have reasonable grounds to suspect that any information that you provide, is false, inaccurate, or otherwise violates these Terms, then we may suspend or terminate your Account or deny you access to all or part of the Services. Any suspension or termination will not affect your obligations to us, including any payment obligations to us, and you will not be entitled to a refund of any payments. Upon suspension or termination of your access to the Services, or upon notice from us, your License to use the Services will terminate immediately.</p>
                       <p>B. Communications. When you communicate with us electronically, such as via a Services communication tool, you consent to receive communications from us electronically. Please note that we will do our best to respond to your inquiry, but it may take us some time. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
                       <p>C. Operation of Services; International Issues. We control and operate the Services from the U.K. If you use the Services from other locations, you are responsible for compliance with applicable local laws regarding your online conduct and acceptable content, if and to the extent local laws apply (e.g., any local education regulatory or data privacy laws). You and we disclaim any application of the Convention on Contracts for the International Sale of Goods.</p>
                       <p>D. Severability; Interpretation. If any provision of these Terms, or any Additional Terms, is for any reason deemed unenforceable by a court or arbitrator, you agree that every attempt will be made to give effect to the parties’ intentions as reflected in that provision, and the remaining provisions contained in this Agreement will continue in full force and effect. You agree that these Terms, and Additional Terms, will not be construed against us because we drafted them.</p>
                       <p>E. Assignment. We may assign our rights and obligations under these Terms, or any Additional Terms, in whole or in part, to any party at any time without any notice. These Terms, and any Additional Terms, may not be assigned by you, and you may not delegate your duties under them.</p>
                       <p>F. No Waiver. No waiver by us of any of these Terms will be of any force or effect unless made in writing and signed by a duly authorized officer of Monkimun Inc.</p>
                       <p>G. Updates to Terms. We reserve the right to modify these Terms, or any Additional Terms, from time to time in our sole discretion (“Updated Terms”). You agree that any Updated Terms will be effective immediately upon our posting them on the Services provided that (i) any modification to Section 6 related to dispute resolution shall not apply to any Dispute initiated prior to the applicable modification, and (ii) any modification to provisions related to fees and billing shall not apply to fees incurred prior to the applicable modification. If you do not cancel your Account with in 7 days after receiving notice of Updated Terms as described above, or if you continue to use the Services after receiving notice of Updated Terms, you agree to comply with, and be bound by, the Updated Terms.</p>
                       <p>H. Survival. In the event of any termination of these Terms, whether by you or the Company, the following Sections will continue in full force and effect: Section 4 (Content You Submit), including but not limited to the Company’s right to use Your Content, Section 5(Services and Content Use Restric tions), Section 6 (Linking to and from Our Services), Section 7 (Governing Law; including Arbitration and Dispute Resolution), Section 8 (Disclaimer of Representations and Warranties), Section 9 (Limitations of Liability), Section 10 (Indemnity), Section 11 (Infringement Policy and Reporting Procedure), Section 13 (Submission of Feedback), and Section 14 (General Provisions).</p>
                       <p>I. Entire Agreement. These Terms constitute the entire agreement and understanding between Company concerning the subject matter of the Terms and supersedes all prior agreements and understandings of the parties with respect to that subject matter. To the extent that anything in or associated with the Service is in conflict or inconsistent with these Terms, these Terms shall take precedence.</p>
                       <p>Contact Us. If you have any questions or concerns with respect to these Terms or the Services, you may contact us through the following URL: <a href="https://ne-games.com/contact" target="_blank">Contact</a></p>
                    </div>
                 
                                      </div>



        </div>

        
      </div>
    </>
  )
}
